# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: sftpupload@1
  inputs:
    sourceFolder: './'
    contents: '**/httpd.conf'
    targetFolder: '/tmp'
    host: '46.137.237.28'
    port: '22'
    username: '$(TargetUserID)'
    password: '$(TargetPassword)'
    displayName: 'Upload Config File'

- task: sftpupload@1
  inputs:
    sourceFolder: './'
    contents: '**/index.html'
    targetFolder: '/tmp'
    host: '46.137.237.28'
    port: '22'
    username: '$(TargetUserID)'
    password: '$(TargetPassword)'
    displayName: 'Upload Dummy File'
