# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, Welcome to My Demo!
  displayName: 'Run a one-line script'

- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: $(Conjur.URL)
    conjuraccount: $(Conjur.Account)
    conjurusername: $(Conjur.User)
    conjurapikey: $(Conjur.API)
    ignoreSsl: true
    
- bash: |
    echo Target Username: $(TargetUserID)
    echo Target Password: $(TargetPassword)
   
- task: sftpupload@1
  inputs:
    sourceFolder: './'
    contents: '**/httpd.conf'
    contents: '**/index.html'
    targetFolder: '/tmp'
    host: '46.137.237.28'
    port: '22'
    username: '$(TargetUserID)'
    password: '$(TargetPassword)'
    displayName: 'Upload Config File'
