# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: 'https://dapmasterdev.sytes.net'
    conjuraccount: 'mycompany'
    conjurusername: 'jolly'
    conjurapikey: '18n8nm52pt6xy02bbxs5a3b6gepmng6d5n2r3q9f4yd028b2v7chmq'
    ignoreSsl: true
    
- bash: |
    echo "Using an input-macro works: $(nonSecretVariable)"
    echo "Using the env var directly does not work: $AzureAPI
    echo "Using a global secret var mapped in the pipeline does not work either: $nonSecretVariable"
    echo "Using a global non-secret var mapped in the pipeline works: $nonSecretVariable" 
    echo "Using the mapped env var for this task works and is recommended: $MY_MAPPED_ENV_VAR"
  env:
    MY_MAPPED_ENV_VAR: $(mySecret)

